spring:
  datasource:
    hikari:
      username: postgres
      password: зщыепкуы
    url: jdbc:postgresql:js_engine
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        use_second_level_cache: true
        cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      org.hibernate.envers:
        revision_type_field_name: rev_type
        do_not_audit_optimistic_locking_field: false
        store_data_at_delete: true
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
